# Generated by Django 5.2 on 2025-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_topic_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='collection',
        ),
        migrations.AddField(
            model_name='question',
            name='collections',
            field=models.ManyToManyField(related_name='questions', to='tracker.questioncollection'),
        ),
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
