# Generated by Django 5.2 on 2025-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_question_collection_question_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.URLField(),
        ),
    ]
